"use client";

import { useEffect, useState } from "react";
import { api, formatApiError } from "@/lib/api-client";
import { useSession } from "@/stores/session.store";
import { Alert, PageHeader } from "@/components/ui/primitives";
import { SalesTable, type SalesLead } from "@/features/sales/SalesTable";
import { RequireCustomerDesk } from "@/features/desk/DeskServices";

export default function DistributorSalesPage() {
  const token = useSession((s) => s.token);
  const [rows, setRows] = useState<SalesLead[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    if (token) api<SalesLead[]>("/api/v1/sales", { token }).then(setRows).catch((e) => setError(formatApiError(e, "Could not load sales")));
  }, [token]);
  return (
    <RequireCustomerDesk fallbackHref="/distributor/overview">
    <div className="space-y-6">
      <PageHeader title="Sales" description="Leads generated by retailers in your network." />
      {error && <Alert tone="error">{error}</Alert>}
      <SalesTable rows={rows} detailBase="/distributor/sales" />
    </div>
    </RequireCustomerDesk>
  );
}
